common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "femnist"
  data_cache_dir: "/home/vinuni/vinuni/user/tuan.nm/uni-fedml/fedml-v0.7.0/data/femnist"  
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "cnn"
  model_file_cache_folder: "./femnist_10_5_256" # will be filled by the server automatically
  global_model_file_path: "./femnist_10_5_256/global_model.pt"


train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 10
  client_num_per_round: 5
  comm_round: 1000
  epochs: 1
  batch_size: 256
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  momentum: 0.0
  lr_schedule: None
  lr_step_size: 1
  lr_milestones: [1000, 2000, 3000]
  lr_decay_rate: 0.1
  nesterov: False
  server_optimizer: sgd
  server_lr: 1.0
  wd: 0.001
  ci: 0
  server_momentum: 0.9
  initialize_all_clients: False
  cache_client_status: False

fedprox_args:
  fedprox_mu: 0.1


fednova_args:
  gmf: 0.0
  mu: 0.0
  dampening: 0.0

feddyn_args:
  feddyn_alpha: 1.0

validation_args:
  frequency_of_the_test: 5

device_args:
  using_gpu: true
  gpu_id: 0
  device_type: "gpu"
  process_id: 0

comm_args:
  backend: "sp"
  is_mobile: 0



tracking_args:
  # the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: True
  wandb_entity: mtuann
  wandb_key: 7c39ee8a10915ff3c0c5ab24ade88e9ea871fb69
  wandb_project: bench_optim
  wandb_name: femnist_cnn_10_5_256
  run_name: femnist_cnn_10_5_256
  wandb_only_server: True
  using_mlops: False

attack_args:
  enable_attack: false
  attack_type: None

defense_args:
  enable_defense: False
  defense_type: norm_diff_clipping
  norm_bound: 5.0



